name: rezerwacja_miejsc
description: "Rezerwacja miejsc"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.0.0
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.9.0
  file_picker: ^7.1.0
  sign_in_with_apple: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/login_background.png